# Generated by Django 3.2.19 on 2025-05-30 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shop_port1.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Nummer')),
            ],
            options={
                'verbose_name': 'Warengruppe',
                'verbose_name_plural': 'Warengruppen',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewe', models.BooleanField(default=False)),
                ('stonier', models.BooleanField(default=False)),
                ('transaktion', models.IntegerField()),
                ('laufende_nr', models.IntegerField()),
                ('leistungsdatum', models.DateField(blank=True, default=shop_port1.models.default_date, null=True)),
                ('erstellt_am', models.DateField(blank=True, default=shop_port1.models.default_date, null=True)),
                ('periode', models.CharField(max_length=10)),
                ('schluessel', models.CharField(max_length=10)),
                ('produkt', models.CharField(max_length=10)),
                ('bezeichnung', models.CharField(max_length=255)),
                ('buch_kz', models.CharField(default='00', max_length=2)),
                ('bw_k', models.CharField(default='00', max_length=2)),
                ('menge', models.IntegerField()),
                ('l_einheit', models.CharField(max_length=10)),
                ('l_gw', models.IntegerField()),
                ('lageplatz', models.CharField(max_length=5)),
                ('lagerplatz', models.CharField(max_length=10)),
                ('kostenstelle', models.CharField(max_length=10)),
                ('kostenstelle_bezeichnung', models.CharField(max_length=255)),
                ('kostenart', models.CharField(max_length=10)),
                ('erstellt_von', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_port1.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('bank_transfer', 'Banküberweisung')], max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='shop_port1.CartItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop_port1.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArticleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('number', models.CharField(max_length=20, verbose_name='Nummer')),
                ('productgroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop_port1.productgroup', verbose_name='Produkt-Gruppe')),
            ],
            options={
                'verbose_name': 'Artikelgruppe',
                'verbose_name_plural': 'Artikelgruppen',
            },
        ),
    ]
