# Generated by Django 3.2.19 on 2025-05-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_port1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlegroup',
            options={'ordering': ['productgroup', 'number'], 'verbose_name': 'Artikelgruppe', 'verbose_name_plural': 'Artikelgruppen'},
        ),
    ]
