# Generated by Django 3.2.19 on 2025-05-30 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop_port1', '0002_alter_articlegroup_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlegroup',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Bezeichnung'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Nummer')),
                ('designation', models.CharField(max_length=100, verbose_name='Bezeichnung')),
                ('inventory', models.IntegerField(verbose_name='Bestand')),
                ('minmum_inventory', models.IntegerField(verbose_name='Mindestbestand')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Einkaufs-Preis')),
                ('articlegroup', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='shop_port1.articlegroup', verbose_name='Artikelgruppe')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
            },
        ),
    ]
