# Generated by Django 5.1.3 on 2025-06-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0003_auto_20250530_1135"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Bemerkung"),
        ),
    ]
