# Generated by Django 5.1.3 on 2025-06-03 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0004_article_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Adresse"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Beschreibung"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lieferant",
                "verbose_name_plural": "Lieferanten",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="deliver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="shop_port1.deliver",
                verbose_name="Lieferant",
            ),
        ),
    ]
