# Generated by Django 5.1.3 on 2025-06-09 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0005_deliver_article_deliver"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.AddField(
            model_name="article",
            name="available_for_sale",
            field=models.BooleanField(default=True, verbose_name="Verkaufbar"),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop_port1.article",
            ),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Bezeichnung"),
        ),
    ]
