# Generated by Django 5.1.3 on 2025-06-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shop_port1",
            "0006_remove_cartitem_product_article_available_for_sale_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="productgroup",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="productgroup_images/"
            ),
        ),
    ]
