# Generated by Django 5.1.3 on 2025-06-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0007_productgroup_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="article_images/"),
        ),
    ]
