# Generated by Django 5.1.3 on 2025-06-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0008_article_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="article_images/",
                verbose_name="Produktbild",
            ),
        ),
    ]
