# Generated by Django 5.1.3 on 2025-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0009_alter_article_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="ean",
            field=models.CharField(default="000", max_length=30, verbose_name="EAN"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="articlegroup",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Bezeichnung"),
        ),
        migrations.AlterField(
            model_name="productgroup",
            name="name",
            field=models.CharField(max_length=40, verbose_name="Bezeichnung"),
        ),
    ]
