# Generated by Django 5.1.3 on 2025-06-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0010_article_ean_alter_articlegroup_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="inv_date",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Datum letzte Inventur"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="inventory",
            field=models.IntegerField(verbose_name="Inventurbestand"),
        ),
    ]
