# Generated by Django 5.1.3 on 2025-06-12 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0011_article_inv_date_alter_article_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="inv_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 12, 10, 4, 36, 292308, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Datum letzte Inventur",
            ),
        ),
    ]
