# Generated by Django 5.1.3 on 2025-07-15 10:19

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0012_alter_article_inv_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "verbose_name": "Produkt im Warenkorb",
                "verbose_name_plural": "Produkte im Warenkorb",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="inv_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 15, 10, 19, 20, 142268),
                verbose_name="Datum letzte Inventur",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to="shop_port1.article",
                verbose_name="Produkt",
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1, verbose_name="Anzahl"),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                to="shop_port1.cartitem", verbose_name="Produkt"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Benutzer",
            ),
        ),
    ]
