# Generated by Django 5.1.3 on 2025-07-15 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_port1", "0013_alter_cartitem_options_alter_article_inv_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={
                "ordering": ["user", "article"],
                "verbose_name": "Produkt im Warenkorb",
                "verbose_name_plural": "Produkte im Warenkorb",
            },
        ),
        migrations.AlterField(
            model_name="article",
            name="inv_date",
            field=models.DateTimeField(
                default=datetime.datetime(2025, 7, 15, 10, 43, 32, 436354),
                verbose_name="Datum letzte Inventur",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("paypal", "PayPal"),
                    ("bank_transfer", "Banküberweisung"),
                    ("bar", "Barzahlung"),
                ],
                max_length=50,
            ),
        ),
    ]
